package infra

import (
	"fmt"
	"io"
	"math"
	"math/rand"
	"net/http"
	"os"
	"runtime"
	"strings"
	"sync"
	"time"

	"github.com/google/uuid"
)

// Handler is an in-process backend function: it takes JSON-ish params from the
// frontend and returns a JSON-ish result. It runs inside the window process —
// no subprocess, no socket.
type Handler func(req map[string]any) (map[string]any, error)

// HandlerRegistry holds in-process backend handlers callable from the frontend
// via BACKEND.call(name, params, cb).
type HandlerRegistry struct {
	mu       sync.Mutex
	handlers map[string]Handler
	store    map[string]any
}

func (r *HandlerRegistry) Register(name string, h Handler) { r.handlers[name] = h }

func (r *HandlerRegistry) Has(name string) bool { _, ok := r.handlers[name]; return ok }

func (r *HandlerRegistry) Dispatch(name string, req map[string]any) (map[string]any, error) {
	h, ok := r.handlers[name]
	if !ok {
		return nil, fmt.Errorf("no in-process handler %q", name)
	}
	if req == nil {
		req = map[string]any{}
	}
	return h(req)
}

// BuiltinHandlers returns a registry preloaded with generally useful handlers,
// so a window app (e.g. one generated by Capy) has real backend calls without
// any external process. Add app-specific handlers in this same Go process.
func BuiltinHandlers() *HandlerRegistry {
	r := &HandlerRegistry{handlers: map[string]Handler{}, store: map[string]any{}}

	r.Register("echo", func(req map[string]any) (map[string]any, error) {
		return req, nil
	})

	r.Register("time", func(req map[string]any) (map[string]any, error) {
		now := time.Now()
		return map[string]any{
			"iso":  now.Format(time.RFC3339),
			"unix": now.Unix(),
			"time": now.Format("15:04:05"),
			"date": now.Format("2006-01-02"),
		}, nil
	})

	r.Register("uuid", func(req map[string]any) (map[string]any, error) {
		return map[string]any{"value": uuid.NewString()}, nil
	})

	r.Register("random", func(req map[string]any) (map[string]any, error) {
		max := toFloat(req["max"], 100)
		return map[string]any{"value": rand.Float64() * max, "int": rand.Intn(int(max) + 1)}, nil
	})

	r.Register("math", func(req map[string]any) (map[string]any, error) {
		a, b := toFloat(req["a"], 0), toFloat(req["b"], 0)
		var v float64
		switch fmt.Sprint(req["op"]) {
		case "add":
			v = a + b
		case "sub":
			v = a - b
		case "mul":
			v = a * b
		case "div":
			if b != 0 {
				v = a / b
			}
		case "pow":
			v = math.Pow(a, b)
		case "mod":
			if b != 0 {
				v = math.Mod(a, b)
			}
		default:
			return nil, fmt.Errorf("unknown op %v", req["op"])
		}
		return map[string]any{"value": v}, nil
	})

	r.Register("sysinfo", func(req map[string]any) (map[string]any, error) {
		host, _ := os.Hostname()
		return map[string]any{
			"os": runtime.GOOS, "arch": runtime.GOARCH,
			"cpus": runtime.NumCPU(), "hostname": host, "go": runtime.Version(),
		}, nil
	})

	r.Register("reverse", func(req map[string]any) (map[string]any, error) {
		s := []rune(fmt.Sprint(req["text"]))
		for i, j := 0, len(s)-1; i < j; i, j = i+1, j-1 {
			s[i], s[j] = s[j], s[i]
		}
		return map[string]any{"value": string(s)}, nil
	})

	// In-memory key/value store (process lifetime), useful for app state that
	// should outlive a page navigation.
	r.Register("store.set", func(req map[string]any) (map[string]any, error) {
		r.mu.Lock()
		defer r.mu.Unlock()
		r.store[fmt.Sprint(req["key"])] = req["value"]
		return map[string]any{"ok": true}, nil
	})
	r.Register("store.get", func(req map[string]any) (map[string]any, error) {
		r.mu.Lock()
		defer r.mu.Unlock()
		return map[string]any{"value": r.store[fmt.Sprint(req["key"])]}, nil
	})
	r.Register("store.keys", func(req map[string]any) (map[string]any, error) {
		r.mu.Lock()
		defer r.mu.Unlock()
		keys := make([]string, 0, len(r.store))
		for k := range r.store {
			keys = append(keys, k)
		}
		return map[string]any{"keys": keys}, nil
	})

	// http.get — fetch a URL from the Go process (no browser CORS limits).
	r.Register("http.get", func(req map[string]any) (map[string]any, error) {
		url := fmt.Sprint(req["url"])
		if !strings.HasPrefix(url, "http") {
			return nil, fmt.Errorf("invalid url")
		}
		resp, err := http.Get(url)
		if err != nil {
			return nil, err
		}
		defer resp.Body.Close()
		b, _ := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
		return map[string]any{"status": resp.StatusCode, "body": string(b)}, nil
	})

	return r
}

func toFloat(v any, def float64) float64 {
	switch n := v.(type) {
	case float64:
		return n
	case int:
		return float64(n)
	case int64:
		return float64(n)
	case string:
		var f float64
		if _, err := fmt.Sscanf(n, "%g", &f); err == nil {
			return f
		}
	}
	return def
}
